name: Package Application with Pyinstaller
"on":
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          src/requirements*.txt
    - name: Install Dependencies
      run: |
        pip install -r src/requirements.txt
    - name: Build Executable
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        onefile: true
        script-name: container-image-replicator.py
        standalone: true
        working-directory: src
    - name: Rename binary removing the .bin extension from Nuitka's default
      run: |
        if [ ${{ runner.os }} == 'Linux' ]; then
          mv src/build/container-image-replicator.bin src/build/container-image-replicator.linux
        elif [ ${{ runner.os }} == 'macOS' ]; then
          mv src/build/container-image-replicator.bin src/build/container-image-replicator.mac
        fi
    - name: ${{ runner.os }} Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        fail_on_unmatched_files: false
        files: |
          src/build/container-image-replicator.exe
          src/build/container-image-replicator
          src/build/*.container-image-replicator.app/**/*
